# Generated by Django 5.1.4 on 2024-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moezurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
